### ISSUE TITLE
CTRL-SHIFT

### ISSUE THREAD

**Issue by nicklit** [HaydenMeloche/USB-Rubber-Ducky-Toolkit#1]
I believe this is a valid command in DuckyScript. Saw Darren use it here -> https://github.com/hak5darren/USB-Rubber-Ducky/wiki/Attacking-Windows-At-The-Logon-Screen,---Gaining-Access-To-CMD-With-System-Privileges.
I do not believe we can support it yet, and I'm having trouble using CTRL SHIFT ENTER also.

**Comment by HaydenMeloche** [comment]
covered under #10
