### ISSUE TITLE
Check script is still there before encoding

### ISSUE THREAD

**Issue by HaydenMeloche** [HaydenMeloche/USB-Rubber-Ducky-Toolkit#13]
When `formEncoding` loads, it copies over the current script to Duckys location. There is no check that the file is there before it goes and loads CMD with this file. This will most likely not be a problem but if the user deletes the script after loading formEncode it will break the encode button.
Idea for fix:

1. Create function in main class that copies the file. 
2. Call that function before the formEncode opens
3. When user clicks encode, check the file is still there and if it isn't then fun the function from 1.

**Comment by nicklit** [comment]
@HaydenMeloche Your version looked like it was creating a "script.txt" and then immediately deleting it if it existed. My thought was to delete anything that is there beforehand, then create a "script.txt" in its place. I still don't think it's perfect as I still get an error in the debug console when encoding the file, although it may work. I do not have my ducky on me currently to check if the .bin file is legitimate

**Comment by nicklit** [comment]
Currently, the debug console spits "Error: " with no error attached. Maybe that's just bad syntax, looking into it

**Comment by nicklit** [comment]
I realized the Error: I was reading in Console was just messy debug statements. Cleaning that up now. Please also verify my commit here is logical @HaydenMeloche

**Comment by HaydenMeloche** [comment]
Reverted to original
