### ISSUE TITLE
File exists always fails 2nd try (confirming bin file was created)

### ISSUE THREAD

**Issue by HaydenMeloche** [HaydenMeloche/USB-Rubber-Ducky-Toolkit#3]
In the btnEncode button at the bottom the code 
 `MessageBox.Show(File.Exists(outPutFilePath) ? "Bin file created sucessfully." : "Error creating file.");`
Works the first time it is run. But never works again until I close and re-open program. 

I have tried doing `Thread.Sleep(1500);` before this above code because I originally thought it was to checking before cmd completed but I have ruled this out.

**Comment by nicklit** [comment]
Changed the value of outPutFilePath a bit. I believe it was affected by where your Repository was sitting, will submit the code and explain later tonight when I am able!
